server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@kosta_medium?TNS_ADMIN=/home/ec2-user/oracle_wallet
    username: admin
    password: Apluskosta!!123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: oracle
    database-platform: org.hibernate.dialect.Oracle10gDialect
logging:
  level:
    org:
      hibernate: info
    jambo:
      controller: debug
file:
  urlPath: /img
  path: /home/ec2-user/img/
